#!/usr/bin/env python

s = input("Enter your DNA sequence: ")

acount = 0
ccount = 0
gcount = 0
tcount = 0

for nt in s:
    if nt == "A":
        acount +=1
    elif nt == "C":
        ccount +=1
    elif nt == "G":
        gcount +=1
    elif nt == "T":
        tcount +=1

print(acount, ccount, gcount, tcount)

