#!/usr/bin/env python
# coding=utf-8


#Problem

#Figure 2. The Hamming distance between these two strings is 7. Mismatched symbols are colored red.
#Given two strings s and t of equal length, the Hamming distance between s and t, denoted dH(s,t), is the number of corresponding symbols that differ in s and t. See Figure 2.

#Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).

#Return: The Hamming distance dH(s,t).

#Sample Dataset
#GAGCCTACTAACGGGAT
#CATCGTAATGACGGCCT


def reverse_complement(s):
    complements = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
    return ''.join([complements[c] for c in reversed(s)])


def reverse_palindromes(s):
    results = []

    l = len(s)

    for i in range(l):
        for j in range(4, 9):

            if i + j > l:
                continue

            s1 = s[i:i+j]
            s2 = reverse_complement(s1)

            if s1 == s2:
                results.append((i + 1, j))

    return results


if __name__ == "__main__":

    small_dataset = "TCAATGCATGCGGGTCTATATGCAT"
    large_dataset = open('datasets/rosalind_revp.txt').read().strip()

    results = reverse_palindromes(large_dataset)

    print "\n".join([' '.join(map(str, r)) for r in results])
